source: src
target: www
indexTemplate: src/index-template.html
postTemplate: src/post-template.html
overwrite: false
versionFile: package.json
order: descending
maxImageDimension: 1000
execute: git add . && git commit -a -m "💬 blog update `date`" && git push