source: src
target: www
indexTemplate: src/index-template.html
postTemplate: src/post-template.html
overwrite: true
versionFile: package.json
execute: git add . && git commit -a -m "💬 blog update `date`" && git push